name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests
      - name: Test
        run:  dotnet test v4/src/LibrarySystem/UnitTests/UnitTests.csproj
        
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: v4/src/LibrarySystem/UnitTests/TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}  
        
      - name: Build images
        timeout-minutes: 10
        run: docker compose -f v4/src/LibrarySystem/docker-compose.yml build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose -f v4/src/LibrarySystem/docker-compose.yml up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      # TODO setup variant, service and port

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
